### ISSUE TITLE
Chapter 19, Installing Git

### ISSUE THREAD

**Issue by ILeftTheLaw** [calthoff/self_taught#10]
I installed Git via their website (Windows version).  However, typing "git" into Bash continues to tell me git is not installed, although it clearly is and I can run it.

I think the problem I'm experiencing has to do with where bash is installed on my computer. I can't find it so I don't know what part of my PC's directory tree I'm in.  I'm completely lost here because I don't know what directory I have to be in to, e.g., download packages as in Chapter 18, or, clone repositories as in Chapter 19.

**Comment by calthoff** [comment]
@ILeftTheLaw Sorry for the delay. I've been on vacation. I do not use Windows, so I am not the best person to troubleshoot this. If you post this question in my Facebook group, Self-Taught Programmers, someone will be able to help you: https://www.facebook.com/groups/selftaughtprogrammers.
