### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by Aegis-Imperio** [calthoff/self_taught#11]
Attempting to do the python_ex8.py

in the beginning of the book. It is the example of a "good comment" where the command is supposed to give the diagonal of a rectangle. I have tried typing it, copying it, and saving it and running the module but no matter what I do the command gives me no output. It just produces "RESTART: C:/Users/Censoredfoldername/AppData/Local/Programs/Python/Python36-32/b" and then a new line of >>>

I am getting the same issue with python_ex27.py

I do

1. 
2. b = 100
3. b

and after running the module I receive no output. If I then enter B alone I will be given the value of 100. So the module gives the information but for some reason the value of b in the module does not prompt it to produce 100. I have to ask for B separate from the module.

**Comment by calthoff** [comment]
In the first example, there is not supposed to be any output. You need to run the second example from the shell.
