### ISSUE TITLE
Syntax error while using result while using Python 3.7.0a4 shell

### ISSUE THREAD

**Issue by arunchandy** [calthoff/self_taught#16]
After  naming and defining function, python is not taking result line. The error is attached. Lines look like this
>>> def f(x):
	return x * 2
result = f(2)
SyntaxError: invalid syntax
>>> 
![j9dctwl](https://user-images.githubusercontent.com/35811083/35402037-35038f90-01f3-11e8-94d9-d5479db8480d.PNG)

**Comment by calthoff** [comment]
You have to hit enter first after you type the function. Then you type result = f(2). Or don't use the shell and save the program in IDLE.

**Comment by arunchandy** [comment]
Thanks....but its still not working on shell. I saved in IDLE, that's the only way its running.
