### ISSUE TITLE
Import module1 not hello?

### ISSUE THREAD

**Issue by cogginproductions** [calthoff/self_taught#3]
In the book, you say to create a new file called "module1.py" and import it into a 2nd file called "module2.py", but the code says to "import hello" not "import module1". That could lead to confusion.

**Comment by calthoff** [comment]
@cogginproductions Thanks for pointing this out. You are right. I will make that clearer.

**Comment by cogginproductions** [comment]
You're welcome and thank you. Glad I could help!
