### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by mikebriones** [calthoff/self_taught#5]
Running into an issue on: https://github.com/calthoff/self_taught/blob/master/python_ex74.py
where after I type in 'if x % 2 == 0:' I get a syntax error. When I copy and paste, all the code, I get an error saying 'SyntaxError: invalid syntax' and the if from that line is highlighted. The only way I can get that line to work is by copying and pasting just that line. Any idea why this is happening?

**Comment by calthoff** [comment]
@mikebriones I just retested that example. Worked fine on my end. I am not sure what is happening. Make sure your spacing is correct (4 spaces). If you are still stuck, please send a Git Gist with your code in it.

**Comment by kdbates** [comment]
I get Invalid syntax error running the ex3
```
>>> for i in range(100):
    print("Hello, Kitty!")
```
