### ISSUE TITLE
page 13 typo

### ISSUE THREAD

**Issue by kdbates** [calthoff/self_taught#7]
You probably already know this and not sure if I should bring this to your attention... 
You have a hash character caught up in an &lt;a&gt; tag on page 13.  Screen shot here.
![p13-typo](https://cloud.githubusercontent.com/assets/399956/26561142/c6a793c4-4470-11e7-80c1-ea7c3052a796.png)

**Thanks for your work. I appreciate the book.**

**Comment by calthoff** [comment]
@kdbates The hashtag is a comment in Python. I put it there on purpose because the URL is part of the code and it needs the hashtag to be valid Python. You are welcome! Thanks for buying it!
