### ISSUE TITLE
Example keeps asking me to save even after I save...

### ISSUE THREAD

**Issue by MKimble515** [calthoff/self_taught#8]
``x = 100
if x == 10:
    print("10!")
elif x == 20:
    print("20!")
else:
    print("I don’t know!")

if x == 100:
    print("x is 100!")

if x % 2 == 0:
    print("x is even!")
else:
    print("x is odd!")

When I use the F5 key to run(in the test editor), I keep getting a message to save. This doesn't happen with other code, just this particular one.  Update- I retyped the code myself and it worked fine. I tried repeatedly to be able to save the code above using copy and paste, but for some reason it would not save it.

**Comment by calthoff** [comment]
@MKimble515 Weird. Not sure what happened!

**Comment by Sir-Python-Damselrot** [comment]
Sometimes I run into this and I have noticed it does so when I inadvertently open or Ctrl + N two or more documents. If you close them all and restart IDLE Shell (Ctrl + F6) it often corrects this squirrely behavior.
